apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: dXNlcg==
  MONGO_INITDB_ROOT_PASSWORD: dXNlcjEyMw==
  MONGO_URI: bW9uZ29kYjovL3VzZXI6dXNlcjEyM0Btb25nby1zZXJ2aWNlOjI3MDE3Lw==
  JWT_SECRET: M2ZAKDlrbDIkekg4XlBRd1ImNypZdE4wb1YhbUpk
